version: '2'
services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: sorame_bot
        volumes:
            - ./my.cnf:/etc/mysql/my.cnf
            - /var/lib/mysql
        restart: always
    web:
        image: ubuntu:16.04
        volumes :
            - ./:/bot
        depends_on:
            - db
        working_dir: /bot
        command: ./bot
        restart: always
