db:
  image: mysql:5.7
  container_name: mysql
  environment:
    MYSQL_ROOT_PASSWORD: password
  volumes:
    - ./my.cnf:/etc/mysql/my.cnf
app:
    build: .
    container_name: sorame_bot
    depends_on:
        - db

