version: '2'
services:
    db:
      image: mysql:5.7
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: password
      volumes:
        - ./my.cnf:/etc/mysql/my.cnf
      restart: always
      expose:
          - 3306
      volumes:
          - ./mysql_data:/var/lib/mysql
    web:
        build: .
        container_name: sorame_bot
        depends_on:
            - db
        restart: always

